/* SPDX-License-Identifier: Apache-2.0 */
/* Generated from index.html by tools/gen_page.py - do not edit. */

#ifndef REFLOW_INDEX_HTML_H_
#define REFLOW_INDEX_HTML_H_

static const char index_html[] =
	"<!DOCTYPE html>\n"
	"<html lang='en'>\n"
	"<head>\n"
	"<meta charset='utf-8'>\n"
	"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
	"<title>Reflow oven</title>\n"
	"<style>\n"
	"body{font:14px system-ui,sans-serif;margin:0;padding:16px;background:#111;color:#eee}\n"
	"h1{font-size:18px;margin:0 0 12px}\n"
	"#temp{font-size:44px;font-weight:600;line-height:1}\n"
	"#sub{color:#aaa;margin:4px 0 12px}\n"
	"button,select{font:inherit;padding:8px 14px;margin:0 6px 6px 0;border:0;border-radius:6px;background:#2b6;color:#031;cursor:pointer}\n"
	"button.stop{background:#c53;color:#fff}\n"
	"button.warn{background:#666;color:#fff}\n"
	"canvas{width:100%;height:220px;background:#000;border-radius:6px;margin-top:12px}\n"
	".bad{color:#f66;font-weight:600}\n"
	"table{border-collapse:collapse;margin-top:12px;width:100%;max-width:420px}\n"
	"td{padding:3px 8px 3px 0;color:#bbb}\n"
	"td.v{color:#eee;text-align:right}\n"
	"</style>\n"
	"</head>\n"
	"<body>\n"
	"<h1>Reflow oven</h1>\n"
	"<div id='temp'>--.- &deg;C</div>\n"
	"<div id='sub'>connecting...</div>\n"
	"<div>\n"
	"<select id='prof'></select>\n"
	"<button onclick='cmd(\"start\")'>Start</button>\n"
	"<button class='stop' onclick='cmd(\"stop\")'>Stop</button>\n"
	"<button class='warn' onclick='cmd(\"clear\")'>Clear fault</button>\n"
	"</div>\n"
	"<canvas id='c' width='640' height='220'></canvas>\n"
	"<table>\n"
	"<tr><td>setpoint</td><td class='v' id='sp'>-</td></tr>\n"
	"<tr><td>duty</td><td class='v' id='duty'>-</td></tr>\n"
	"<tr><td>stage</td><td class='v' id='stage'>-</td></tr>\n"
	"<tr><td>elapsed</td><td class='v' id='el'>-</td></tr>\n"
	"</table>\n"
	"<script>\n"
	"var hist=[],MAXP=600,profs=[],lastProf=-1;\n"
	"function cmd(id){var q='/api/cmd?id='+id;if(id=='profile')q+='&arg='+document.getElementById('prof').value;fetch(q,{method:'POST'});}\n"
	"document.getElementById('prof').onchange=function(){cmd('profile');};\n"
	"function fmt(t){var s=Math.floor(t/1000),m=Math.floor(s/60);return m+':'+('0'+(s%60)).slice(-2);}\n"
	"function draw(){\n"
	" var c=document.getElementById('c'),g=c.getContext('2d');\n"
	" g.clearRect(0,0,c.width,c.height);\n"
	" var max=260,h=c.height,w=c.width;\n"
	" g.strokeStyle='#333';g.beginPath();\n"
	" for(var t=0;t<=250;t+=50){var y=h-t/max*h;g.moveTo(0,y);g.lineTo(w,y);}\n"
	" g.stroke();\n"
	" if(hist.length<2)return;\n"
	" var n=hist.length,dx=w/Math.max(n-1,1);\n"
	" function line(key,col){g.strokeStyle=col;g.lineWidth=2;g.beginPath();\n"
	"  for(var i=0;i<n;i++){var y=h-Math.max(hist[i][key],0)/max*h;i?g.lineTo(i*dx,y):g.moveTo(i*dx,y);}g.stroke();}\n"
	" line('sp','#57f');line('t','#2b6');\n"
	"}\n"
	"function update(d){\n"
	" document.getElementById('temp').innerHTML=(d.temp_mc/1000).toFixed(1)+' &deg;C';\n"
	" var s=d.state+(d.fault!='none'?' - FAULT: '+d.fault:'');\n"
	" var sub=document.getElementById('sub');sub.textContent=s;\n"
	" sub.className=d.fault!='none'?'bad':'';\n"
	" document.getElementById('sp').textContent=d.setpoint_mc?(d.setpoint_mc/1000).toFixed(0)+' C':'-';\n"
	" document.getElementById('duty').textContent=(d.duty/10).toFixed(0)+' %';\n"
	" document.getElementById('stage').textContent=d.stage_name+' ('+(d.n_stages?d.stage+1:0)+'/'+d.n_stages+')';\n"
	" document.getElementById('el').textContent=fmt(d.total_ms);\n"
	" if(d.profile!=lastProf){lastProf=d.profile;document.getElementById('prof').value=d.profile;}\n"
	" hist.push({t:d.temp_mc/1000,sp:d.setpoint_mc/1000});\n"
	" if(hist.length>MAXP)hist.shift();\n"
	" if(d.state!='running'&&hist.length>1&&d.setpoint_mc==0&&hist.length>MAXP)hist=[];\n"
	" draw();\n"
	"}\n"
	"fetch('/api/profiles').then(function(r){return r.json();}).then(function(j){\n"
	" profs=j.profiles;var sel=document.getElementById('prof');\n"
	" profs.forEach(function(p,i){var o=document.createElement('option');o.value=i;o.textContent=p;sel.appendChild(o);});\n"
	"});\n"
	"var es=new EventSource('/api/events');\n"
	"es.onmessage=function(e){update(JSON.parse(e.data));};\n"
	"es.onerror=function(){document.getElementById('sub').textContent='link lost, retrying...';};\n"
	"</script>\n"
	"</body>\n"
	"</html>\n";

#endif /* REFLOW_INDEX_HTML_H_ */
