# SPDX-License-Identifier: Apache-2.0
#
# index_html.h is generated from src/net/index.html at build time (RFO-B25).
#
# It used to be a committed header regenerated by hand with tools/gen_page.py.
# Nothing in the build tied the two together, so the only thing keeping them in
# step was somebody remembering - and the failure was silent in the worst way:
# edit index.html, forget the script, and the firmware keeps serving the old
# page while tools/test_page.js exercises the new one and passes. Green tests,
# fixed page, and an operator still looking at the bug.
#
# Included by the application and by every test image that links httpd.c, so
# there is one rule and not two that can drift.
#
# The header lands in the build tree and nowhere else. A copy in src/net/ would
# win over this one - a quoted #include looks next to the including file first -
# so .gitignore keeps it from coming back and tests/tools/test_index_html.py
# fails if it does.

function(reflow_generate_index_html app_root)
  set(gen_dir ${CMAKE_CURRENT_BINARY_DIR}/generated/reflow)
  set(page ${app_root}/src/net/index.html)
  set(script ${app_root}/tools/gen_page.py)
  set(header ${gen_dir}/index_html.h)

  add_custom_command(
    OUTPUT ${header}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${gen_dir}
    COMMAND ${PYTHON_EXECUTABLE} ${script} ${page} ${header}
    # The script is a dependency as well: changing how the page is escaped has
    # to regenerate the header, not wait for the page to change too.
    DEPENDS ${page} ${script}
    COMMENT "Generating index_html.h from src/net/index.html"
    VERBATIM
  )

  add_custom_target(reflow_index_html DEPENDS ${header})
  add_dependencies(app reflow_index_html)
  target_include_directories(app PRIVATE ${gen_dir})
endfunction()
